// Generated by tools/generate-scancode
const char scancode_to_ascii[256] = {
  0,    // scancode   0
  27,   // scancode   1 - "\e"
  49,   // scancode   2 - "1"
  50,   // scancode   3 - "2"
  51,   // scancode   4 - "3"
  52,   // scancode   5 - "4"
  53,   // scancode   6 - "5"
  54,   // scancode   7 - "6"
  55,   // scancode   8 - "7"
  56,   // scancode   9 - "8"
  57,   // scancode  10 - "9"
  48,   // scancode  11 - "0"
  45,   // scancode  12 - "-"
  61,   // scancode  13 - "="
  127,  // scancode  14 - 127
  9,    // scancode  15 - "\t"
  113,  // scancode  16 - "q"
  119,  // scancode  17 - "w"
  101,  // scancode  18 - "e"
  114,  // scancode  19 - "r"
  116,  // scancode  20 - "t"
  121,  // scancode  21 - "y"
  117,  // scancode  22 - "u"
  105,  // scancode  23 - "i"
  111,  // scancode  24 - "o"
  112,  // scancode  25 - "p"
  91,   // scancode  26 - "["
  93,   // scancode  27 - "]"
  10,   // scancode  28 - "\n"
  0,    // scancode  29
  97,   // scancode  30 - "a"
  115,  // scancode  31 - "s"
  100,  // scancode  32 - "d"
  102,  // scancode  33 - "f"
  103,  // scancode  34 - "g"
  104,  // scancode  35 - "h"
  106,  // scancode  36 - "j"
  107,  // scancode  37 - "k"
  108,  // scancode  38 - "l"
  59,   // scancode  39 - ";"
  39,   // scancode  40 - "'"
  96,   // scancode  41 - "`"
  0,    // scancode  42
  92,   // scancode  43 - "\\"
  122,  // scancode  44 - "z"
  120,  // scancode  45 - "x"
  99,   // scancode  46 - "c"
  118,  // scancode  47 - "v"
  98,   // scancode  48 - "b"
  110,  // scancode  49 - "n"
  109,  // scancode  50 - "m"
  44,   // scancode  51 - ","
  46,   // scancode  52 - "."
  47,   // scancode  53 - "/"
  0,    // scancode  54
  0,    // scancode  55
  0,    // scancode  56
  32,   // scancode  57 - " "
  0,    // scancode  58
  0,    // scancode  59
  0,    // scancode  60
  0,    // scancode  61
  0,    // scancode  62
  0,    // scancode  63
  0,    // scancode  64
  0,    // scancode  65
  0,    // scancode  66
  0,    // scancode  67
  0,    // scancode  68
  0,    // scancode  69
  0,    // scancode  70
  0,    // scancode  71
  0,    // scancode  72
  0,    // scancode  73
  0,    // scancode  74
  0,    // scancode  75
  0,    // scancode  76
  0,    // scancode  77
  0,    // scancode  78
  0,    // scancode  79
  0,    // scancode  80
  0,    // scancode  81
  0,    // scancode  82
  0,    // scancode  83
  0,    // scancode  84
  0,    // scancode  85
  60,   // scancode  86 - "<"
  0,    // scancode  87
  0,    // scancode  88
  0,    // scancode  89
  0,    // scancode  90
  0,    // scancode  91
  0,    // scancode  92
  0,    // scancode  93
  0,    // scancode  94
  0,    // scancode  95
  0,    // scancode  96
  0,    // scancode  97
  0,    // scancode  98
  0,    // scancode  99
  0,    // scancode 100
  0,    // scancode 101
  0,    // scancode 102
  0,    // scancode 103
  0,    // scancode 104
  0,    // scancode 105
  0,    // scancode 106
  0,    // scancode 107
  0,    // scancode 108
  0,    // scancode 109
  0,    // scancode 110
  0,    // scancode 111
  0,    // scancode 112
  0,    // scancode 113
  0,    // scancode 114
  0,    // scancode 115
  0,    // scancode 116
  0,    // scancode 117
  0,    // scancode 118
  0,    // scancode 119
  0,    // scancode 120
  0,    // scancode 121
  0,    // scancode 122
  0,    // scancode 123
  0,    // scancode 124
  0,    // scancode 125
  0,    // scancode 126
  0,    // scancode 127
  0,    // scancode 128
  0,    // scancode 129
  0,    // scancode 130
  0,    // scancode 131
  0,    // scancode 132
  0,    // scancode 133
  0,    // scancode 134
  0,    // scancode 135
  0,    // scancode 136
  0,    // scancode 137
  0,    // scancode 138
  0,    // scancode 139
  0,    // scancode 140
  0,    // scancode 141
  0,    // scancode 142
  0,    // scancode 143
  0,    // scancode 144
  0,    // scancode 145
  0,    // scancode 146
  0,    // scancode 147
  0,    // scancode 148
  0,    // scancode 149
  0,    // scancode 150
  0,    // scancode 151
  0,    // scancode 152
  0,    // scancode 153
  0,    // scancode 154
  0,    // scancode 155
  0,    // scancode 156
  0,    // scancode 157
  0,    // scancode 158
  0,    // scancode 159
  0,    // scancode 160
  0,    // scancode 161
  0,    // scancode 162
  0,    // scancode 163
  0,    // scancode 164
  0,    // scancode 165
  0,    // scancode 166
  0,    // scancode 167
  0,    // scancode 168
  0,    // scancode 169
  0,    // scancode 170
  0,    // scancode 171
  0,    // scancode 172
  0,    // scancode 173
  0,    // scancode 174
  0,    // scancode 175
  0,    // scancode 176
  0,    // scancode 177
  0,    // scancode 178
  0,    // scancode 179
  0,    // scancode 180
  0,    // scancode 181
  0,    // scancode 182
  0,    // scancode 183
  0,    // scancode 184
  0,    // scancode 185
  0,    // scancode 186
  0,    // scancode 187
  0,    // scancode 188
  0,    // scancode 189
  0,    // scancode 190
  0,    // scancode 191
  0,    // scancode 192
  0,    // scancode 193
  0,    // scancode 194
  0,    // scancode 195
  0,    // scancode 196
  0,    // scancode 197
  0,    // scancode 198
  0,    // scancode 199
  0,    // scancode 200
  0,    // scancode 201
  0,    // scancode 202
  0,    // scancode 203
  0,    // scancode 204
  0,    // scancode 205
  0,    // scancode 206
  0,    // scancode 207
  0,    // scancode 208
  0,    // scancode 209
  0,    // scancode 210
  0,    // scancode 211
  0,    // scancode 212
  0,    // scancode 213
  0,    // scancode 214
  0,    // scancode 215
  0,    // scancode 216
  0,    // scancode 217
  0,    // scancode 218
  0,    // scancode 219
  0,    // scancode 220
  0,    // scancode 221
  0,    // scancode 222
  0,    // scancode 223
  0,    // scancode 224
  0,    // scancode 225
  0,    // scancode 226
  0,    // scancode 227
  0,    // scancode 228
  0,    // scancode 229
  0,    // scancode 230
  0,    // scancode 231
  0,    // scancode 232
  0,    // scancode 233
  0,    // scancode 234
  0,    // scancode 235
  0,    // scancode 236
  0,    // scancode 237
  0,    // scancode 238
  0,    // scancode 239
  0,    // scancode 240
  0,    // scancode 241
  0,    // scancode 242
  0,    // scancode 243
  0,    // scancode 244
  0,    // scancode 245
  0,    // scancode 246
  0,    // scancode 247
  0,    // scancode 248
  0,    // scancode 249
  0,    // scancode 250
  0,    // scancode 251
  0,    // scancode 252
  0,    // scancode 253
  0,    // scancode 254
  0,    // scancode 255
};
